---
# YAML formatted list of actions to install chainlink
# NB If this script errors out while gathering facts, its almost certainly because APT is running update daemon on the guests
# This can happen just after boot. Just try it again - it only needs to run successfully once. You can ssh into the machine 
# as well to check whether its APT 
# TODO put in an error check for this and perform retry

- hosts: 192.168.33.15
  gather_facts: false
  pre_tasks:
# installing python2 with raw shell commands before we can use apt.
  - name: Install python2 for full ansible functionality - NB not installed by default on Ubuntu Xenial - Can be ommitted on distros that ship with python 2.7
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup: 
# BEGIN OPTIONAL 
# Choice of administrative tools. caveat - they reduce operational complexity but increase attack surface
  tasks:
  - name: Update repositories cache and install screen from apt - screen makes interaction over ssh significantly easier
    apt:
      name: screen
      update_cache: yes
    become: true
  - name: Install tcpdump from apt - Useful to monitor traffic ad hoc
    apt: 
      name: tcpdump
    become: true
  - name: Install htop from apt - info rich and lets us know whats running on our box at a glance if we are  concerned with malware or intrusion
    apt: 
      name: htop
    become: true
# END OPTIONAL

  - name: Set PATH in /etc/environment to include /usr/lib/go-1.9/bin and remove ubuntu games directories while we're about it
    lineinfile:
      path: /etc/environment
      regexp: '^PATH'
      line: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/go-1.9/bin:/home/vagrant/go"
    become: true
  - name: Set GOPATH in /etc/environment to be /home/vagrant/go 
    lineinfile:
      path: /etc/environment
      line: GOPATH=/home/vagrant/go
  - name: Create a /home/vagrant/go/bin dir for dep install script
    file:
      path: /home/vagrant/go/bin
      state: directory
#      mode: +x
  - name: Load the ppa repo for go from google
    apt_repository:
      repo: 'ppa:gophers/archive'
  - name: Install go1.9 using apt command
    apt:
      name: golang-1.9-go
      update_cache: yes
  - name: Get dep online install script and make it executable
    get_url: 
      url: https://raw.githubusercontent.com/golang/dep/master/install.sh
      dest: /home/vagrant
      mode: +x
  - name: Run the online dep install script 
    command: /home/vagrant/install.sh creates=/home/vagrant/go/bin/dep
    become: true
  - name: Download Chainlink from Smartcontract github, check its not already downloaded first.
    command: /usr/lib/go-1.9/bin/go get -d github.com/smartcontractkit/chainlink creates=/home/vagrant/go/src/github.com/smartcontractkit/
    become: true
  - name: Install chainlink using make install in its dir, checking its not already installed first
    command: make install creates="/home/vagrant/go/bin/chainlink" 
    args:
      chdir: "/home/vagrant/go/src/github.com/smartcontractkit/chainlink"
    environment: 
      GOPATH: '/home/vagrant/go'
      PATH: '/home/vagrant/bin:/home/vagrant/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/lib/go-1.9/bin:/home/vagrant/go:/home/vagrant/go/bin:/snap/bin' 
    become: true

  - name: iptables - allow tcp in on port 8545
    iptables: 
      chain: INPUT
      protocol: tcp
      destination_port: 8545
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT
      comment: all ip tables rules on this machine added by ansible. Managed thru the playbooks.
    become: yes
  - name: iptables - allow tcp out on port 8545
    iptables:
      chain: OUTPUT
      protocol: tcp
      source_port: 8545
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT
    become: yes

  - name: iptables - allow tcp replies on port 22
    iptables:
      chain: OUTPUT
      protocol: tcp
      source_port: 22
      ctstate: ESTABLISHED
      jump: ACCEPT
    become: yes


  - name: iptables - allow tcp in on port 22
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 22
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT
    become: yes

  - name: iptables - allow dns tcp traffic out
    iptables:
      chain: OUTPUT
      protocol: tcp
      destination_port: 53
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT
    become: yes

  - name: iptables - allow dns tcp replies in
    iptables:
      chain: INPUT
      protocol: tcp
      source_port: 53
      ctstate: ESTABLISHED
      jump: ACCEPT
    become: yes

  - name: iptables - allow dns udp traffic out
    iptables:
      chain: OUTPUT
      protocol: udp
      destination_port: 53
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT
    become: yes

  - name: iptables - allow dns udp replies in
    iptables:
      chain: INPUT
      protocol: udp
      source_port: 53
      ctstate: ESTABLISHED
      jump: ACCEPT
    become: yes

  - name: iptables - drop all other traffic on INPUT
    iptables:
      chain: INPUT
      policy: DROP
    become: yes

  - name: iptables - drop all other traffic on OUTPUT
    iptables:
      chain: OUTPUT
      policy: DROP
    become: yes

  - name: iptables - drop all traffic from forwarding
    iptables:
      chain: FORWARD
      policy: DROP
    become: yes


#  - name: Use apt-get to install firewalld as per the STIG requirements
#    apt:
#      name: firewalld
#      update_cache: yes

#  - import_role:
#      name: ansible-hardening

...
