---
- hosts: linkies
  tasks: 
  - name: Iptables - allow all TCP OUT on port 6688 for CHAINLINK
    iptables: 
      chain: INPUT
      protocol: tcp
      destination_port: 6688
      jump: ACCEPT
    become: yes
  - name: Iptables - allow all TCP OUT on port 6688 for CHAINLINK
    iptables:
      chain: OUTPUT
      protocol: tcp
      source_port: 6688
      jump: ACCEPT
    become: yes
  - name: Iptables - allow all UDP OUT on port 6688 for CHAINLINK
    iptables:
      chain: INPUT
      protocol: udp
      destination_port: 6688
      jump: ACCEPT
    become: yes
  - name: Iptables - allow all UDP OUT on port 6688 for CHAINLINK
    iptables:
      chain: OUTPUT
      protocol: udp
      source_port: 6688
      jump: ACCEPT
    become: yes
  - name: Iptables - allow TCP IN on port 22 for SSH
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 22
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT
    become: yes
  - name: Iptables - allow TCP replies on port 22 for SSH
    iptables:
      chain: OUTPUT
      protocol: tcp
      source_port: 22
      ctstate: ESTABLISHED
      jump: ACCEPT
    become: yes
  - name: Iptables - allow DNS TCP traffic OUT
    iptables:
      chain: OUTPUT
      protocol: tcp
      destination_port: 53
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT
    become: yes

  - name: Iptables - allow DNS TCP replies IN in response
    iptables:
      chain: INPUT
      protocol: tcp
      source_port: 53
      ctstate: ESTABLISHED
      jump: ACCEPT
    become: yes
  - name: Iptables - allow DNS UDP traffic OUT
    iptables:
      chain: OUTPUT
      protocol: udp
      destination_port: 53
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT
    become: yes
  - name: Iptables - allow DNS UDP replies IN in response
    iptables:
      chain: INPUT
      protocol: udp
      source_port: 53
      ctstate: ESTABLISHED
      jump: ACCEPT
    become: yes
  - name: Iptables - allow HTTP TCP OUT for UPDATES, GITHUB, etc
    iptables:
      chain: OUTPUT
      protocol: tcp
      destination_port: 80
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT
    become: yes
  - name: Iptables - allow HTTP TCP back IN for UPDATES, GITHUB, etc
    iptables:
      chain: INPUT
      protocol: tcp
      source_port: 80
      ctstate: ESTABLISHED
      jump: ACCEPT
    become: yes
  - name: Iptables - allow HTTPS TCP OUT for UPDATES and GITHUB
    iptables:
      chain: OUTPUT
      protocol: tcp
      destination_port: 443
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT
    become: yes
  - name: Iptables - allow HTTPS TCP back IN for UPDATES and GITHUB
    iptables:
      chain: INPUT
      protocol: tcp
      source_port: 443
      ctstate: ESTABLISHED
      jump: ACCEPT
    become: yes

  - name: Iptables - DROP ALL other traffic on default INPUT chain
    iptables:
      chain: INPUT
      policy: DROP
    become: yes
  - name: Iptables - DROP ALL other traffic on default OUTPUT chain
    iptables:
      chain: OUTPUT
      policy: DROP
    become: yes
  - name: Iptables - DROP ALL traffic from default FORWARDING chain
    iptables:
      chain: FORWARD
      policy: DROP
    become: yes
  - name: Install iptables-persistent to run rules at boot in future
    apt: 
      name: iptables-persistent
    become: yes
#  - name: Save the iptables configuration 
#    shell: 'sudo iptables-save > /etc/iptables/rules.v4' 
#    become: yes

#  - import_role:
#      name: ansible-hardening
...
