---
- hosts: links
  tasks:

  - name: update the cache 
    apt:
      update_cache: yes

  - name: ============================Get go 1.16 for x64 / PC =======================
    get_url:
      url: https://golang.org/dl/go1.16.2.linux-amd64.tar.gz
      dest: /home/vitaly/go1.16.2.linux-amd64.tar.gz
      mode: +x

#  - name: ================Uncomment to Get go for raspberry pi  =======================
#    get_url:
#      url: https://golang.org/dl/go1.16.2.linux-amd64.tar.gz
#      dest: /home/vitaly/go1.16.2.linux-amd64.tar.gz
#      mode: +x

  - name: ==== Set PATH in /etc/environment to include usr/local/go/bin ====
    lineinfile:
      path: /etc/environment
      regexp: '^PATH'
      line: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin"
    become: true

  - name: ============================Install Node JS=======================
    snap:
      name: node
      classic: yes
###################INSTALL GO##############################################

  - name: Install Go
    ansible.builtin.unarchive:  
      src: /home/vitaly/go1.16.2.linux-amd64.tar.gz
      dest: /usr/local
      remote_src: yes


  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/home/ubuntu/go/bin"
    GOPATH: "/usr/local/go"

...
