---
- hosts: links
#  roles:
#    - geerlingguy.nodejs

  tasks:

  - name: update the cache
    apt:
      update_cache: yes
  
  # overly permissive below
  - name: ============================mkdir for CL in usr/local =======================
    ansible.builtin.file:
      path: /home/sergey/chainlink
      state: directory
      mode: '0775'
#      become: yes

  - name: ============= Add the user sergey  ==============
    ansible.builtin.user:
      name: sergey
      shell: /bin/bash
      comment: management account
#      group: admin

  - name: ========Download go 1.15 for x64 / PC =======================
    get_url:
      url: https://golang.org/dl/go1.15.11.linux-amd64.tar.gz
      dest: /home/sergey/goinstaller.tar.gz
#      mode: +x
      checksum: sha256:8825b72d74b14e82b54ba3697813772eb94add3abf70f021b6bdebe193ed01ec

#  - name: =========Alternately Uncomment to Get go for Arm / Raspberry Pi  =======================
#    get_url:
#      url: https://golang.org/dl/go1.15.11.linux-arm64.tar.gz
#      dest: /home/vitaly/go16.tar.gz
#      mode: +x
#      checksum: sha256:bfc8f07945296e97c6d28c7999d86b5cab51c7a87eb2b22ca6781c41a6bb6f2d

  - name: ==== For Ubuntu Set PATH in /etc/environment to include usr/local/go/bin ====
    lineinfile:
      path: /etc/environment
      regexp: '^PATH'
      line: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin"
    become: true

  - name: ========================== untar Go =======================
    ansible.builtin.unarchive:
      src: /home/sergey/goinstaller.tar.gz
      dest: /usr/local
      remote_src: yes
  
############      Install node snap with classic confinement       #################
  - name: Snap Install "node" channel 12 with option --classic
    snap:
      name: node
      classic: yes
      channel: '12'

################ install yarn ###################

  - name: Install yarn node.js package
    community.general.npm:
      name: yarn
      path: /app/location
      global: yes

################ install postgres ###################
################ (It needs a reboot for psql to finish install / appear?  ###################

  - name: Install postgresql packages, make, screen, and htop db and host management tools from ubuntu apt
    apt:
      pkg:
      - postgresql
      - postgresql-contrib
      - make
      - htop
      - screen
# below seems to install most of the GUI - avoid ? -
# it certainly turns on power saving - 20 minute sleep timer, which will have to be disabled by hand
##      - pgadmin3

  - name: Clone chainlink from https://github.com/smartcontractkit/chainlink
    ansible.builtin.git:
      repo: https://github.com/smartcontractkit/chainlink
      dest: /home/sergey/chainlink


  - name: Install packages based on package.json.
    community.general.yarn:
      path: /home/sergey/chainlink

...
