---
- hosts: ethers
  tasks:

  - name: update the cache 
    apt:
      update_cache: yes

  - name: =================================Get go 1.16 =======================
    get_url:
      url: https://golang.org/dl/go1.16.2.linux-amd64.tar.gz
      dest: /home/vitalik/go1.16.2.linux-amd64.tar.gz
      mode: +x

  - name: ==== Set PATH in /etc/environment to include usr/local/go/bin ====
    lineinfile:
      path: /etc/environment
      regexp: '^PATH'
      line: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin"
    become: true
###################INSTALL NODEJS##############################################

  - name: ============================Install Node JS=======================
    snap:
      name: node
      classic: yes
###################INSTALL GO##############################################

  - name: Install Go
    ansible.builtin.unarchive:  
      src: /home/vitalik/go1.16.2.linux-amd64.tar.gz
      dest: /usr/local
      remote_src: yes

###################INSTALL GETH##############################################

  - name: ===================== Add Geth PPA  ===============
  ansible.builtin.apt_repository:
    repo: ppa:ethereum/ethereum

  - name: ===================== install geth ===============
    command: go install github.com/ethereum/go-ethereum/cmd/geth  
    become: yes

  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/home/vitalik/go/bin"
    GOPATH: "/usr/local/go"

...
