---
  - name: Python3 is installed.
    ansible.builtin.apt:
      update_cache: yes  
      name: python3
    become: yes

  - name: /etc/environment PATH includes usr/local/go/bin and /usr/local/node-v{{ nodejs_version }}-linux-x64/bin
    lineinfile:
      path: /etc/environment
      regexp: '^PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin'
      line: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/home/{{ ansible_user }}/go/bin:/usr/local/bin/node-v{{ nodejs_version }}-linux-x64/bin"
    become: true

  - name: chainlink credentials file location set in /etc/environment to enable optional automatic startup of cl go exe
    lineinfile:
      path: /etc/environment
      regexp: '^ADMIN_CREDENTIALS_FILE'
      line: ADMIN_CREDENTIALS_FILE="/path/to/credentials/file"
    become: true

  - name: $GOBIN folder set in /etc/environment 
    lineinfile:
      path: /etc/environment
      regexp: '^GOBIN'
      line: GOBIN="/home/{{ ansible_user }}/go/bin"
    become: true

  - name: '{{ go_tar_gz }} unarchived into /usr/local'  
    ansible.builtin.unarchive:
      src: '{{ go_tar_gz }}'
      dest: /usr/local
      owner: root
    become: true

  - name: '{{ nodejs_tar_gz }} unarchived into usr/local/bin'
    ansible.builtin.unarchive:
      src: '{{ nodejs_tar_gz }}'
      dest: /usr/local/bin
      owner: root

  - name: pnpm installed by npm
    community.general.npm:
      name: pnpm
      path: /usr/local/bin
      global: yes
    environment:
      PATH: /usr/local/bin/node-v{{ nodejs_version }}-linux-x64/bin:{{ ansible_facts.env.PATH }}
    become: true

  - name: chainlink {{ cl_source_version }} cloned into /home/{{ ansible_user }}/chainlink
    ansible.builtin.git:
      repo: https://github.com/smartcontractkit/chainlink
      dest: "/home/{{ ansible_user }}/chainlink"
      version: v2.7.2

  - name: make install the chainlink source code
    command:
      cmd:  make install
    args:
      chdir: "/home/{{ ansible_user }}/chainlink"
      creates: "/home/{{ ansible_user }}/go/bin/chainlink"
    register: cl_make_output

  - name: print output from chainlink build to terminal
    ansible.builtin.debug:
      msg: "{{ cl_make_output }}" 

...
