# -bane config v0.9
#
---
  - name: PATH in /etc/environment includes usr/local/go/bin and /usr/local/node-v{{ node_version }}-linux-x64/bin
    lineinfile:
      path: /etc/environment
      regexp: '^PATH'
      line: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin/go:/usr/local/bin/node-v{{ node_version }}-linux-x64/bin"
    become: true

  - name: go installed in /usr/local from the files directory on management server  
    ansible.builtin.unarchive:
      src: ./files/go.tar.gz
      dest: /usr/local/bin
      owner: root
    become: true

  - name: node unarchived from management server into usr/local/bin
    ansible.builtin.unarchive:
      src: ./files/node.tar.gz
      dest: /usr/local/bin
      owner: root
      creates: /usr/local/bin/node
    become: true

  - name: yarn installed by npm
    community.general.npm:
      name: yarn
      path: /usr/local/bin
      global: yes
    environment:
      PATH: /usr/local/bin/node-v{{ node_version }}-linux-x64/bin:{{ ansible_facts.env.PATH }}
    become: true

  - name: chainlink dir cloned from https://github.com/smartcontractkit/chainlink
    ansible.builtin.git:
      repo: https://github.com/smartcontractkit/chainlink
      dest: /home/cia/chainlink


  - name: Install packages based on package.json.
    community.general.yarn:
      path: /home/cia/chainlink
      version: 'v1.1.1'
    environment:
      PATH: /usr/local/bin/node-v{{ node_version }}-linux-x64/bin:{{ ansible_facts.env.PATH }}
      production: yes
      
...
