################ install postgres ###################
################ (It needs a reboot for psql to finish install / appear?  ###################
  - name: Install postgresql packages from ubuntu apt
    become: yes
    apt:
      pkg:
      - postgresql
      - postgresql-contrib
